server:
  servlet:
    context-path: /test
  port: 8081

spring:
  rabbitmq:
    addresses: amqp://Jesse:Jesse@localhost:5672/test
    connection-timeout: 10000
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
